apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-login-deployment
spec:
  replicas:  3
  selector:
    matchLabels:
      app: login-service
  template:
    metadata:
      labels:
        app: login-service
    spec:
      containers:
      - name: login-service
        image: wechatacrname.azurecr.io/azure-login-service:1.0.0
        envFrom:
        - configMapRef:
            name: spring-login-config
        ports:
        - containerPort:  8080
        resources:
          requests:
            cpu: "200m"
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: azure-login-vote-front
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: spring-login-deployment
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
